export const HOME = '/'
export const SIGNUP = '/signup'
export const SIGNIN = '/signin'
export const BOOKING = '/booking'
export const CART = '/cart'
export const PAYMENT_SUCCESS = '/payment-success'
export const RESET_PASSWORD = '/reset-password'
export const NOTFOUND = '/*'