export const LANDING = '/'
export const SIGNUP = '/signup'
export const SIGNIN = '/signin'
export const HOME = '/home'
export const BOOK = '/book'
export const PAYMENT = '/payment'
export const CONFIRMATION = '/confirmation'